name: Lint & Test
on: push
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            **/.svelte-kit
          key: deps-cache-${{ hashFiles('**/pnpm-lock.yaml') }}

  lint:
    runs-on: ubuntu-latest
    needs: install
    if: ${{ needs.install.result == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            **/.svelte-kit
          key: deps-cache-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Lint
        run: pnpm run lint

  vitest:
    runs-on: ubuntu-latest
    needs: [install]
    if: ${{ needs.lint.result == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            **/.svelte-kit
          key: deps-cache-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Run unit tests
        run: pnpm run test

  playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: [install]
    if: ${{ needs.unit-tests.result == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            **/.svelte-kit
          key: deps-cache-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install firebase
        run: pnpm install -g firebase-tools

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        run: firebase emulators:start --import emulator_seed 'pnpm exec playwright test'

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
